-- =============================================================================
-- 002_trades.sql
-- Phase 1: Trade lifecycle tables.
--
-- Key design decision: proposed_trades and trades are SEPARATE tables.
-- A proposed_trade is a signal generated by an agent — it has NO effect on
-- any account until a human approves it (or, far later, an explicit
-- automated-execution policy is turned on for a specific proven strategy).
-- A trade only exists once it has actually been placed. This physically
-- enforces "AI never touches your money" at the schema level, not just
-- in application logic that could have a bug.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- proposed_trades
-- Signals generated by research/strategy agents. Nothing here is live.
-- Every row must pass through risk validation (recorded in risk_violations
-- if blocked) and then explicit human approval before it can reference a
-- row in `trades`.
-- -----------------------------------------------------------------------------
CREATE TABLE proposed_trades (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    account_id          UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    generated_by        TEXT NOT NULL,          -- agent/strategy name, e.g. 'trend_following_v1'
    symbol              TEXT NOT NULL,
    asset_class         TEXT NOT NULL CHECK (asset_class IN (
                             'forex', 'stocks', 'etf', 'index', 'commodity',
                             'precious_metal', 'energy', 'fixed_income', 'crypto'
                         )),
    direction            TEXT NOT NULL CHECK (direction IN ('long', 'short')),
    proposed_entry_price NUMERIC(18,6),
    proposed_stop_loss   NUMERIC(18,6),
    proposed_take_profit NUMERIC(18,6),
    proposed_size         NUMERIC(18,6) NOT NULL CHECK (proposed_size > 0),
    proposed_risk_pct     NUMERIC(5,2),          -- % of account equity at risk if stop is hit
    rationale             TEXT NOT NULL,          -- required: no signal without a stated reason
    strategy_tag           TEXT,
    timeframe               TEXT,                   -- 'intraday' | 'swing' | 'position' | 'long_term'

    -- Risk gate outcome (set by validation code before this can be approved)
    risk_check_status     TEXT NOT NULL DEFAULT 'pending' CHECK (risk_check_status IN ('pending', 'passed', 'blocked')),
    risk_check_notes       TEXT,

    -- Human approval gate — this is THE switch referenced in the governing
    -- principle. status only becomes 'approved' via explicit human action.
    status                 TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN (
                                'pending_review', 'approved', 'rejected', 'expired'
                            )),
    reviewed_by             TEXT,
    reviewed_at              TIMESTAMPTZ,
    rejection_reason         TEXT,

    expires_at                TIMESTAMPTZ,           -- stale signals shouldn't linger in the approval queue
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_proposed_trades_pending ON proposed_trades(account_id, status) WHERE status = 'pending_review';
CREATE INDEX idx_proposed_trades_created ON proposed_trades(created_at DESC);

COMMENT ON TABLE proposed_trades IS 'Signals only. No connection to real capital. status must be explicitly set to approved by a human before an execution script may act — and even then, only for accounts/strategies where automation has been separately authorized.';

-- -----------------------------------------------------------------------------
-- trades
-- Actual placed trades — paper or live. Every trade should trace back to a
-- proposed_trade where practical (manual discretionary trades are the
-- exception and should be flagged as such via source = 'discretionary').
-- -----------------------------------------------------------------------------
CREATE TABLE trades (
    id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    account_id            UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    proposed_trade_id      UUID REFERENCES proposed_trades(id),  -- NULL only for discretionary trades
    source                  TEXT NOT NULL DEFAULT 'agent_signal' CHECK (source IN ('agent_signal', 'discretionary')),

    symbol                   TEXT NOT NULL,
    asset_class               TEXT NOT NULL CHECK (asset_class IN (
                                   'forex', 'stocks', 'etf', 'index', 'commodity',
                                   'precious_metal', 'energy', 'fixed_income', 'crypto'
                               )),
    direction                  TEXT NOT NULL CHECK (direction IN ('long', 'short')),

    entry_price                 NUMERIC(18,6) NOT NULL,
    stop_loss                    NUMERIC(18,6),
    take_profit                   NUMERIC(18,6),
    size                            NUMERIC(18,6) NOT NULL CHECK (size > 0),
    risk_pct_at_entry               NUMERIC(5,2),      -- % of equity actually risked

    exit_price                       NUMERIC(18,6),
    realized_pnl                      NUMERIC(18,2),
    realized_pnl_pct                   NUMERIC(6,3),

    status                              TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed', 'cancelled')),

    entered_by                          TEXT NOT NULL,   -- trader/owner name or 'auto' once Phase 3+ authorizes it
    entry_platform_ref                  TEXT,            -- broker/platform order ID for reconciliation

    strategy_tag                         TEXT,
    timeframe                             TEXT,
    notes                                   TEXT,

    opened_at                              TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at                               TIMESTAMPTZ,
    created_at                               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_trades_account_status ON trades(account_id, status);
CREATE INDEX idx_trades_account_opened ON trades(account_id, opened_at DESC);
CREATE INDEX idx_trades_symbol ON trades(symbol);

COMMENT ON TABLE trades IS 'Actual placed trades (paper or live, distinguished via accounts.account_type). This is the trading journal — every row here has money (real or paper) attached to it.';

-- Now that trades exists, wire the FK we deferred in 001
ALTER TABLE risk_violations
    ADD CONSTRAINT fk_risk_violations_proposed_trade
    FOREIGN KEY (proposed_trade_id) REFERENCES proposed_trades(id);
